mysql:
  host: 127.0.0.1
  port: 3306
  config: ""
  db: gvb_db
  user: root
  password: jjidm
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
site_info:
  created_at: "2023-02-12"
  bei_an: 湘ICP备2021010654号-3
  title: ZDM的个人博客
  qq_image: http://www.fengfengzhidao.com/static/my/img/footer/qq.png
  version: 6.0.2
  email: 2371522043@qq.com
  wechat_image: http://www.fengfengzhidao.com/static/my/img/footer/wechat.png
  name: DM知道
  job: 启端开发
  addr: 湖南长沙
  slogan: DM知道
  slogan_en: FENGFENGZHIDAO
  web: http://www.fengfengzhidao.com/
  bilibili_url: https://space.bilibili.com/359151217
  gitee_url: https://gitee.com/fengfengzhidao
  github_url: https://github.com/fengfengzhidao/
jwt:
  secret: xxxx
  expires: 48
  issuer: xx
qq:
  app-id: "xx"
  key: xx
  redirect: http://xx.xx.com/login?flag=qq
email:
  host: smtp.qq.com
  port: 465
  user: xxxx@qq.com
  password: xxx
  default_from_email: DM知道
  use-ssl: xx
  user-tls: xx
qi_niu:
  access_key: UMM-xx-FdRIf-xx
  secret_key: xx
  bucket: fengfengzhidao
  cdn: xx://xx.xx.com/
  zone: xx
  size: 5