mysql:
  host: 127.0.0.1
  port: 3306
  config: "?charset=utf8mb4&parseTime=True&loc=Local"
  db: gvb_db
  user: root
  password: jjidm
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
upload:
  size: 6
  path: uploads/file
site_info:
  created_at: "2023-02-12"
  bei_an: 湘ICP备2021010654号-3
  title: ZDM的个人博客
  qq_image: http://www.fengfengzhidao.com/static/my/img/footer/qq.png
  version: 6.0.2
  email: 2371522043@qq.com
  wechat_image: http://www.fengfengzhidao.com/static/my/img/footer/wechat.png
  name: DM知道
  job: 启端开发
  addr: 湖南长沙
  slogan: DM知道
  slogan_en: FENGFENGZHIDAO
  web: http://www.fengfengzhidao.com/
  bilibili_url: https://space.bilibili.com/359151217
  gitee_url: https://gitee.com/fengfengzhidao
  github_url: https://github.com/fengfengzhidao/
qq:
  app_id: ""
  key: xx
  redirect: http://xx.xx.com/login?flag=qq
qi_niu:
  enable: true
  access_key: 694sybYn3EZvWMKPwpNzXwXrVBzk5YAFw-XGc1EI
  secret_key: VQfpbQkJ56Iq3vtpYFwuHwmcjCBl8uXNelHVhBvI
  bucket: jjidm
  cdn: 	snjeuaut0.hd-bkt.clouddn.com
  zone: http(s)://up.qiniup.com
  size: 6
  prefix: gvb
email:
  host: smtp.qq.com
  port: 465
  user: 2371522043@qq.com
  password: xxx
  default_from_email: JJIDM知道
  use_ssl: false
  user_tls: false
jwt:
  secret: xxxxxx
  expires: 48
  issuer: xx
redis:
  ip: 127.0.0.1
  port: 6379
  password: 
  pool_size: 100